sandbox/sail: Added irstlm patch. Renamed configure.in to configure.ac.
There are a few places in irstlm code where variable length arrays of non-POD
types are causing errors with recent standards compliant c++ compilers.

mdiadapt.cpp:1115:16: error: variable length array of non-POD element type
'streampos' (aka 'fpos<mbstate_t>')
  streampos pos[lmsize()+1];
...

This use is not part of the c++ standard. Some compilers like gcc support this
through an extension while others like clang do not. This patch replaces all
VLAs of non-POD types with std::vector.

Also, configure.in is renamed to configure.ac to make recent automake
distributions happy.

git-svn-id: https://svn.code.sf.net/p/kaldi/code/sandbox/sail@3699 5e6a8d80-dfce-4ca6-a32a-6e07a63d50c8